---
# tasks file for generate-kube-config-files

- name: Set cluster context in worker.kubeconfig
  shell: kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://{{ master_priv_ip }}:6443 \
        --kubeconfig=worker.kubeconfig
  args: 
    chdir: "{{ output_dir }}"

- name: Set cluster credentials in worker.kubeconfig
  shell: kubectl config set-credentials system:node:worker \
        --client-certificate=worker.pem \
        --client-key=worker-key.pem \
        --embed-certs=true \
        --kubeconfig=worker.kubeconfig
  args: 
    chdir: "{{ output_dir }}"


- name: Set cluster context in kube-proxy.kubeconfig
  shell: kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://{{ master_priv_ip }}:6443 \
        --kubeconfig=kube-proxy.kubeconfig
  args: 
    chdir: "{{ output_dir }}"

- name: Set cluster credentials in kube-proxy.kubeconfig
  shell: kubectl config set-credentials kube-proxy \
        --client-certificate=kube-proxy.pem \
        --client-key=kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-proxy.kubeconfig
  args: 
    chdir: "{{ output_dir }}"