---
# tasks file for worker-setup

- name: Setup correct hostname
  hostname: 
    name: "{{ host_name }}"

- name: Apt install unzip
  tags:
    - current
  apt:
    name: ['unzip']

- name: Create kube and cni directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/cni/net.d
    - /opt/cni/bin
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes

- name: Copy certificates and private keys to the worker
  tags:
    - current
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '{{ output_dir }}/ca.pem', dest: '/var/lib/kubernetes' }
    - { src: '{{ output_dir }}/worker.kubeconfig', dest: '/var/lib/kubelet/kubeconfig' }
    - { src: '{{ output_dir }}/worker-key.pem', dest: '/var/lib/kubelet/' }
    - { src: '{{ output_dir }}/worker.pem', dest: '/var/lib/kubelet/' }
    - { src: '{{ output_dir }}/worker.kubeconfig', dest: '/var/lib/kubelet/kubeconfig' }
    - { src: '{{ output_dir }}/kube-proxy.kubeconfig', dest: '/var/lib/kube-proxy/kubeconfig' }
    
    
- name: Download kubernetes worker binaries
  tags:
    - current
  get_url:
    url: "{{ item }}"
    dest: /
    remote_src: yes
  with_items:
    - https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubectl
    - https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kube-proxy
    - https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubelet

- name: Copy kubernetes worker binaries to bin folder
  copy: 
    src: "/{{ item }}"
    dest: /usr/local/bin/
    mode: '+x'
    remote_src: yes
  with_items:
    - kube-proxy
    - kubectl
    - kubelet

- name: Download and unarchive cni plugins and containerd
  tags:
    - current
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    remote_src: yes
  with_items:
    - { src: 'https://github.com/containernetworking/plugins/releases/download/v0.8.0/cni-plugins-linux-amd64-v0.8.0.tgz', dst: '/opt/cni/bin/' }
    - { src: 'https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.2.6.linux-amd64.tar.gz', dst: '/' }


- name: Register subnet id from local terraform output
  tags:
    -  current
  local_action: shell terraform output subnet_id chdir="{{ playbook_dir }}/../terraform"
  become: no
  register: terraform_subnet_id


- name: Register vpc cidr from local terraform output
  tags:
    -  current
  local_action: shell terraform output vpc_cidr chdir="{{ playbook_dir }}/../terraform"
  become: no
  register: terraform_vpc_cidr

- name: Template and copy 10-bridge.conf
  template:
    src: templates/10-bridge.tpl
    dest: /etc/cni/net.d/10-bridge.conf

- name: Copy 99-loopback.conf
  copy: 
    src: files/99-loopback.conf
    dest: /etc/cni/net.d/

- name: Template and copy kubelet service
  tags:
    -  current
  template:
    src: templates/kubelet-service.tpl
    dest: /etc/systemd/system/kubelet.service

- name: Template and copy kube proxy service
  tags:
    -  current
  template:
    src: templates/kube-proxy.service.tpl
    dest: /etc/systemd/system/kube-proxy.service