---
# tasks file for controller-setup
- name: Setup correct hostname
  hostname: 
    name: "{{ host_name }}"

- name: Update repositories cache and install "unzip" package
  apt:
    name: unzip
    update_cache: yes

- name: Copy certificates, private keys and secret to the controller
  copy: src={{ item }} dest=/
  with_items:
    - '{{ output_dir }}/ca.pem'
    - '{{ output_dir }}/kubernetes-key.pem'
    - '{{ output_dir }}/kubernetes.pem'
    - '{{ output_dir }}/encryption-config.yaml'


- name: Download and unarchive etcd 3.3.13
  unarchive:
    src: https://github.com/coreos/etcd/releases/download/v3.3.13/etcd-v3.3.13-linux-amd64.tar.gz
    dest: /
    remote_src: yes

- name: Copy etcd execs to bin folder
  copy: 
    src: /etcd-v3.3.13-linux-amd64/{{ item }} 
    dest: /usr/local/bin/
    mode: '+x'
    remote_src: yes
  with_items:
    - etcd
    - etcdctl

- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/etcd
    - /var/lib/etcd

- name: Copy ca and kube keys to etcd
  copy: src={{ item}} dest=/etc/etcd/
  with_items:
    - '{{ output_dir }}/ca.pem'
    - '{{ output_dir }}/kubernetes-key.pem'
    - '{{ output_dir }}/kubernetes.pem'


- name: Create etcd systemd service unit file
  copy:
    dest: "/etc/systemd/system/etcd.service"
    content: |
        [Unit]
        Description=etcd
        Documentation=https://github.com/coreos

        [Service]
        ExecStart=/usr/local/bin/etcd \
            --name {{ host_name }} \
            --cert-file=/etc/etcd/kubernetes.pem \
            --key-file=/etc/etcd/kubernetes-key.pem \
            --peer-cert-file=/etc/etcd/kubernetes.pem \
            --peer-key-file=/etc/etcd/kubernetes-key.pem \
            --trusted-ca-file=/etc/etcd/ca.pem \
            --peer-trusted-ca-file=/etc/etcd/ca.pem \
            --peer-client-cert-auth \
            --client-cert-auth \
            --initial-advertise-peer-urls https://{{ master_priv_ip }}:2380 \
            --listen-peer-urls https://{{ master_priv_ip }}:2380 \
            --listen-client-urls https://{{ master_priv_ip }}:2379,http://127.0.0.1:2379 \
            --advertise-client-urls https://{{ master_priv_ip }}:2379 \
            --initial-cluster-token etcd-cluster-0 \
            --initial-cluster {{ host_name }}=https://{{ master_priv_ip }}:2380 \
            --initial-cluster-state new \
            --data-dir=/var/lib/etcd 
        Restart=on-failure 
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

- name: Start and enable service etcd
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes



- name: Download kubernetes binaries
  get_url:
    url: "{{ item }}"
    dest: /
    remote_src: yes
  with_items:
    - https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kube-apiserver
    - https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kube-controller-manager
    - https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kube-scheduler
    - https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubectl


- name: Copy kubernetes execs to bin folder
  copy: 
    src: "/{{ item }}"
    dest: /usr/local/bin/
    mode: '+x'
    remote_src: yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl