---
# tasks file for controller-setup
- name: Setup correct hostname
  hostname: 
    name: "{{ host_name }}"

- name: Copy certificates and private keys to the controller
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '{{ output_dir }}/ca.pem', dest: '/' }
    - { src: '{{ output_dir }}/kubernetes-key.pem', dest: '/' }
    - { src: '{{ output_dir }}/kubernetes.pem', dest: '/' }