- hosts: kthw-controller
  gather_facts: false
  become: yes
  roles:
    - role: controller-setup
      host_name: master
      output_dir: "{{ playbook_dir }}/output_files"
      master_priv_ip: "{{ groups['kthw-controller-priv'][0] }}"