- hosts: local
  gather_facts: false
  become: no
  connection: local
  roles:
    - role: generate-kube-config-files
      master_priv_ip: groups['kthw-controller-priv'][0]
      input_dir: "{{ playbook_dir }}/input_files"
      output_dir: "{{ playbook_dir }}/output_files"