#- hosts: local
#  gather_facts: false
#  become: no
#  connection: local
#  roles:
#    - role: generate-kube-config-files
#      worker_ext_ip: groups['kthw-worker-1'][0]
#      worker_priv_ip: groups['kthw-worker-1-priv'][0]
#      master_priv_ip: groups['kthw-controller-priv'][0]
#      config_dir: "{{ playbook_dir }}/generate-kube-config-files/files"


- hosts: local
  gather_facts: false
  connection: local
  roles:
    - role: certificate-authority
      input_dir: "{{ playbook_dir }}/input_files"
      output_dir: "{{ playbook_dir }}/output_files"
      worker_ext_ip: groups['kthw-worker-1'][0]
      worker_priv_ip: groups['kthw-worker-1-priv'][0]
      master_priv_ip: groups['kthw-controller-priv'][0]